### ISSUE TITLE
講演タイトルをあつめたい

### ISSUE THREAD

**Issue by takkanm** [asakusarb/oedo10#15]
@inao, @fugakkbn, @hyumanase, @neko314, @yancya, @bash0C7, @amatsuda, @nay, @ogijun
各講演タイトルを集めたいです。このイシューにコメントしてもらえると助かります。

| スピーカー | 講演タイトル |
|---|---|
| @fugakkbn | Days of struggle as a Cop |
| @hyumanase | 造って学んだ発酵食の世界 |
| @neko314 | 観る将、指す将、TyP 〜時を越えた将棋指しの魅力〜 |
| まめさん、ささださん | 朝会 |
| @yancya  | YouTubeチャンネルを支える技術？ |
|  @bash0C7 | 継続的 #RubyMuscleMixin 実践入門 |
| @amatsuda | Hanamiを支える技術 2023 |
| IRB committers | IRB Committers and The World |
| @nay | 『Rubyメソッドかるた』王者への道 〜万葉チームのガチな取り組みを大公開〜 |
| @ogijun | Yet Another Red Gem |
| @inao | WEB+DB PRESSと私 |

**Comment by yancya** [comment]
『YouTubeチャンネルを支える技術？』にしておきます

**Comment by emorima** [comment]
esa の方で更新している内容ですが、私の方で確認している内容です。

| スピーカー | 講演タイトル |
|---|---|
| @fugakkbn | Days of struggle as a Cop |
| @neko314 | 観る将、指す将、TyP　〜時を越えた将棋指しの魅力〜 |
| まめさん、ささださん | 朝会 |
|  @bash0C7 | 継続的 #RubyMuscleMixin 実践入門 |
| IRB committers | IRB Committers and The World |

**Comment by bash0C7** [comment]
https://github.com/asakusarb/oedo10/issues/15#issuecomment-1743929863 の通り、「継続的 #RubyMuscleMixin 実践入門」でお願いします

**Comment by nay** [comment]
大場 (@nay) 、「『Rubyメソッドかるた』王者への道 〜万葉チームのガチな取り組みを大公開〜」でお願いします！

**Comment by ogijun** [comment]
『Yet Another Red Gem』でお願いします！

**Comment by inao** [comment]
> Rubyメソッドかるた』王者への道 〜万葉チームのガチな取り組みを大公開〜

トップの表では`『`が抜けているようです。

**Comment by inao** [comment]
WEB+DB PRESS plusシリーズに寄せた命名にしてくださっている方も多いんですね。
ありがとうございます。

私のタイトルは、いったん「WEB+DB PRESSと私」でお願いできますでしょうか？
（みなさまにならって「WEB+DB PRESSを支える技術」にしようかなーとも思ったのですが、いまの立場でこのタイトルを使うのははばかられるなーと思いまして）

**Comment by neko314** [comment]
自分のタイトル、副題の前が全角スペースなの変だなと思ったので修正しました

**Comment by hyumanase** [comment]
@takkanm 
『造って学んだ発酵食の世界』でお願いします！
遅くなってしまいすみません🙏🏻

**Comment by takkanm** [comment]
みなさん、ありがとうございました。#17 で追加しています。
問題があれば、PR の方で指摘ください。
